package bruhcollective.itaysonlab.ksteam.models.enums

enum class EStoreCategory {
    Reserved0, // kSteam reserved
    Multiplayer,
    Singleplayer,
    Reserved3, // kSteam reserved
    Reserved4, // kSteam reserved
    Reserved5, // kSteam reserved
    ModHL2,
    ModHL,
    VAC,
    Coop,
    Demo,
    Friends,
    HDR, // "HDR Rendring" regarding to SteamDB
    CC,
    Commentary,
    Stats,
    SDK,
    Editor,
    PartialController,
    Mod,
    MMO,
    DLC,
    Achievements,
    Cloud,
    SharedSplitscreen,
    Leaderboards,
    Guide,
    CrossPlatMultiplayer,
    FullController,
    TradingCard,
    Workshop,
    VRThirdParty,
    AsyncGameNotifications,
    SteamController,
    VRSteam,
    InAppPurchases,
    OnlinePvP,
    LocalPvP,
    OnlineCoop,
    LocalCoop,
    SteamVRCollectibles,
    RemotePlayToPhone,
    RemotePlayToTablet,
    RemotePlayToTV,
    RemotePlayTogether,
    CloudGaming,
    CloudGamingNVIDIA,
    LANPvP,
    LANCoop,
    PvP,
    HighQualitySoundtrackAudio,
    SteamChinaWorkshop,
    TrackedControllerSupport,
    VRSupported,
    VROnly,
    PS4ControllerSupport,
    PS4ControllerBTSupport,
    PS5ControllerSupport,
    PS5ControllerBTSupport,
    SteamInputAPI,
    GamepadPreferred,
    HDROutput, // "real" HDR
    FamilySharing,
    SteamTimeline,
}